using System;
using System.Collections.Generic;

namespace SaleBillSystem.NET.Models
{
    /// <summary>
    /// Comprehensive data structure for payment reports
    /// </summary>
    public class PaymentReportData
    {
        // Header Information
        public string ReportTitle { get; set; } = "Payment Settlement Report";
        public DateTime ReportDate { get; set; } = DateTime.Now;
        public string CompanyName { get; set; } = "";
        public string CompanyAddress { get; set; } = "";
        public string CompanyPhone { get; set; } = "";
        
        // Payment Information
        public int PaymentID { get; set; }
        public DateTime PaymentDate { get; set; }
        public string PaymentMethod { get; set; } = "";
        public string Reference { get; set; } = "";
        public decimal TotalPaymentAmount { get; set; }
        
        // Party/Broker Information
        public string PartyName { get; set; } = "";
        public string BrokerName { get; set; } = "";
        public int? PartyID { get; set; }
        public int? BrokerID { get; set; }
        
        // Settlement Summary
        public decimal TotalAmountDue { get; set; }
        public decimal TotalAdvanceUsed { get; set; }
        public decimal TotalCashNeeded { get; set; }
        public decimal TotalInterest { get; set; }
        public decimal TotalDiscount { get; set; }
        public decimal TotalBrokerage { get; set; }
        public decimal UnusedAdvance { get; set; }
        public bool CanFullySettle { get; set; }
        
        // Cheque Details (if applicable)
        public decimal ChequeAmountFirm1 { get; set; }
        public decimal ChequeAmountFirm2 { get; set; }
        public decimal TotalChequeAmount { get; set; }
        
        // Bill Breakdowns
        public List<BillReportDetail> BillDetails { get; set; } = new List<BillReportDetail>();
        
        // Advance Utilizations
        public List<AdvanceUtilizationReport> AdvanceUtilizations { get; set; } = new List<AdvanceUtilizationReport>();
        
        // Unused Advance Reversals
        public List<UnusedAdvanceReversalReport> UnusedAdvanceReversals { get; set; } = new List<UnusedAdvanceReversalReport>();
        
        // Payment Terms Used
        public PaymentTermsReport PaymentTerms { get; set; } = new PaymentTermsReport();
        
        // Generated By
        public string GeneratedBy { get; set; } = "";
        public DateTime GeneratedAt { get; set; } = DateTime.Now;
    }

    /// <summary>
    /// Detailed information for each bill in the payment
    /// </summary>
    public class BillReportDetail
    {
        public int BillID { get; set; }
        public string BillNo { get; set; } = "";
        public string PartyName { get; set; } = "";
        public DateTime BillDate { get; set; }
        public decimal OriginalAmount { get; set; }
        public decimal BalanceDue { get; set; }
        public decimal AmountPaid { get; set; }
        public decimal InterestCharged { get; set; }
        public decimal DiscountEarned { get; set; }
        public decimal Brokerage { get; set; }
        public decimal AdvanceUsed { get; set; }
        public decimal CashUsed { get; set; }
        public string Status { get; set; } = "";
        
        // Interest Period Details
        public List<InterestPeriodReport> InterestPeriods { get; set; } = new List<InterestPeriodReport>();
        
        // Advance Utilizations for this bill
        public List<AdvanceUtilizationDetail> AdvanceUtilizations { get; set; } = new List<AdvanceUtilizationDetail>();
    }

    /// <summary>
    /// Interest period calculation details
    /// </summary>
    public class InterestPeriodReport
    {
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public int Days { get; set; }
        public decimal Principal { get; set; }
        public decimal InterestRate { get; set; }
        public decimal InterestAmount { get; set; }
        public string Description { get; set; } = "";
    }

    /// <summary>
    /// Advance utilization details for a specific bill
    /// </summary>
    public class AdvanceUtilizationDetail
    {
        public int AdvanceID { get; set; }
        public int? UtilizationID { get; set; }
        public DateTime AdvanceDate { get; set; }
        public decimal AdvanceAmount { get; set; }
        public decimal AmountUsed { get; set; }
        public string PaymentMethod { get; set; } = "";
        public string Reference { get; set; } = "";
        public decimal RemainingAmount { get; set; }
    }

    /// <summary>
    /// Overall advance utilization summary
    /// </summary>
    public class AdvanceUtilizationReport
    {
        public int AdvanceID { get; set; }
        // public int? UtilizationID { get; set; } 
        public DateTime AdvanceDate { get; set; }
        public decimal OriginalAmount { get; set; }
        public decimal AmountUsed { get; set; }
        public decimal RemainingAmount { get; set; }
        public string PaymentMethod { get; set; } = "";
        public string Reference { get; set; } = "";
        public string Status { get; set; } = "";
        public List<string> UsedForBills { get; set; } = new List<string>();
    }

    /// <summary>
    /// Unused advance reversal details
    /// </summary>
    public class UnusedAdvanceReversalReport
    {
        public int OriginalAdvanceID { get; set; }
        public int ReversalUtilizationID { get; set; }
        public int OriginalUtilizationID { get; set; }
        public int ReversalAdvanceID { get; set; }
        public string BrokerName { get; set; } = "";
        public decimal OriginalAmount { get; set; }
        public decimal UsedAmount { get; set; }
        public decimal UnusedAmount { get; set; }
        public DateTime ReversalDate { get; set; }
        public string Reference { get; set; } = "";
    }

    /// <summary>
    /// Payment terms used in calculations
    /// </summary>
    public class PaymentTermsReport
    {
        public int InterestDays { get; set; }
        public decimal InterestRate { get; set; }
        public int DiscountDays { get; set; }
        public decimal DiscountRate { get; set; }
        public decimal BrokerageRate { get; set; }
        public string TermsSource { get; set; } = ""; // "Broker", "Default", "Manual"
    }
}
